"""empty message

Revision ID: 1920a4931280
Revises: 1097c563a604
Create Date: 2020-03-22 01:11:33.083449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1920a4931280'
down_revision = '1097c563a604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('test', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'test')
    # ### end Alembic commands ###
